# Generated by Django 5.2.3 on 2025-07-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_evento',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='opcion',
            field=models.CharField(default='otro', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='diaCompletado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
