# Generated by Django 5.2.3 on 2025-07-02 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_fecha_evento_task_opcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='opcion',
        ),
        migrations.AddField(
            model_name='task',
            name='categoria',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='tasks.categoria'),
            preserve_default=False,
        ),
    ]
